"""empty message

Revision ID: 9e43810b272c
Revises: 9c198719be67
Create Date: 2023-02-25 11:28:35.744770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e43810b272c'
down_revision = '9c198719be67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorito', schema=None) as batch_op:
        batch_op.alter_column('planeta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personaje_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
