"""empty message

Revision ID: c0c935800ff9
Revises: d88d53eaf6d0
Create Date: 2023-02-24 04:59:29.646944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0c935800ff9'
down_revision = 'd88d53eaf6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_personaje_name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('favorite_planet_name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('favorite_planet_name')
        batch_op.drop_column('favorite_personaje_name')

    # ### end Alembic commands ###
